version: '2'
services:
  backend:
    image: app-backend:latest
    env_file: "./app-backend.env"
  cron:
    image: app-backend:latest
    env_file: "./app-backend.env"
    command: [ 'crond', '-f' ]
  worker:
    image: app-backend:latest
    env_file: "./app-backend.env"
    command: [ '/usr/bin/supervisord', '-n', '-c', '/etc/supervisor/supervisord.conf' ]
  nginx:
    image: app-nginx:latest
    volumes_from:
      - backend
    depends_on:
      - backend
    ports:
      - "80:80"
    links:
      - backend
